import { NextRequest, NextResponse } from 'next/server'
import { renderToBuffer } from '@react-pdf/renderer'
import { createElement } from 'react'
import { createClient } from '@/lib/supabase/server'
import { db } from '@/db'
import { users, validationReports } from '@/db/schema'
import { eq } from 'drizzle-orm'
import { canUserAccess } from '@/lib/tier-gate'

export async function GET(request: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return new NextResponse('Unauthorized', { status: 401 })

  const allowed = await canUserAccess(user.id, 'canExportPdf')
  if (!allowed) return new NextResponse('Upgrade to Premium to export PDF', { status: 403 })

  const reportId = request.nextUrl.searchParams.get('reportId')
  if (!reportId) return new NextResponse('reportId required', { status: 400 })

  const dbUser = await db.query.users.findFirst({ where: eq(users.supabaseId, user.id) })
  if (!dbUser) return new NextResponse('User not found', { status: 404 })

  const report = await db.query.validationReports.findFirst({ where: eq(validationReports.id, reportId) })
  if (!report || report.userId !== dbUser.id) return new NextResponse('Not found', { status: 404 })

  const { Document, Page, Text, View, StyleSheet } = await import('@react-pdf/renderer')
  const styles = StyleSheet.create({
    page: { padding: 40, backgroundColor: '#FAFAF7', fontFamily: 'Helvetica' },
    header: { marginBottom: 20 },
    title: { fontSize: 24, color: '#0A1628', marginBottom: 4 },
    subtitle: { fontSize: 12, color: '#C8A860', marginBottom: 16 },
    section: { marginBottom: 16 },
    sectionTitle: { fontSize: 14, color: '#0A1628', fontWeight: 'bold', marginBottom: 8, borderBottom: '1px solid #E8E0D0', paddingBottom: 4 },
    text: { fontSize: 10, color: '#1C1C1C', lineHeight: 1.5 },
    score: { fontSize: 36, color: '#C8A860', fontWeight: 'bold' },
    footer: { position: 'absolute', bottom: 20, left: 40, right: 40, borderTop: '1px solid #E8E0D0', paddingTop: 8, flexDirection: 'row', justifyContent: 'space-between' },
    footerText: { fontSize: 8, color: '#C8A860' },
    watermark: { fontSize: 8, color: '#1C1C1C', opacity: 0.4 },
  })

  const reportData = report.reportData as Record<string, unknown>
  const idea = reportData?.idea as Record<string, string> | undefined

  const PdfDoc = () => createElement(Document, null,
    createElement(Page, { size: 'A4', style: styles.page },
      createElement(View, { style: styles.header },
        createElement(Text, { style: styles.title }, `${idea?.name ?? 'Startup'} — Validation Report`),
        createElement(Text, { style: styles.subtitle }, "Aurexa AI Validation | Know it's gold before you dig.")
      ),
      createElement(View, { style: styles.section },
        createElement(Text, { style: styles.sectionTitle }, 'Validation Score'),
        createElement(Text, { style: styles.score }, `${report.overallScore ?? 0}/100`),
        createElement(Text, { style: styles.text }, `Decision: ${report.decision ?? 'N/A'}`),
      ),
      createElement(View, { style: styles.section },
        createElement(Text, { style: styles.sectionTitle }, 'Decision Rationale'),
        ...((report.decisionReasons as string[] ?? [])).map((r, i) =>
          createElement(Text, { key: i, style: styles.text }, `• ${r}`)
        ),
      ),
      createElement(View, { style: styles.section },
        createElement(Text, { style: styles.sectionTitle }, 'Key Risks'),
        ...((report.keyRisks as string[] ?? [])).map((r, i) =>
          createElement(Text, { key: i, style: styles.text }, `• ${r}`)
        ),
      ),
      createElement(View, { style: styles.section },
        createElement(Text, { style: styles.sectionTitle }, 'Integrity Note'),
        createElement(Text, { style: styles.text }, (reportData?.integrityNote as string) ?? ''),
      ),
      createElement(View, { style: styles.footer },
        createElement(Text, { style: styles.footerText }, 'aurexa.app'),
        createElement(Text, { style: styles.watermark }, 'Generated by Aurexa AI | ASSUMPTIONS and PROJECTIONS are labeled throughout'),
      ),
    )
  )

  const buffer = await renderToBuffer(createElement(PdfDoc))
  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="aurexa-validation-${reportId.slice(0,8)}.pdf"`,
    },
  })
}